name: cef
dependencies:
  #build_native: ^0.0.9
  build_native:
    path: ../build_native/build_native
dev_dependencies:
  build_runner:
    git:
      url: https://github.com/thosakwe/build.git
      path: build_runner
      ref: experimental-hot-reloading
